timeout: 1800s
steps:

# Publishing base, cc, and static as latest is handled in a separate release process
- name: gcr.io/cloud-builders/bazel
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace

    bazel clean --host_force_python=PY2 --curses=no
    bazel build --host_force_python=PY2 //package_manager:dpkg_parser.par

- name: gcr.io/cloud-builders/bazel
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace

    bazel run --host_force_python=PY2 //experimental/nodejs
    bazel run --host_force_python=PY2 //experimental/nodejs:debug

- name: gcr.io/cloud-builders/docker
  entrypoint: sh
  args:
  - -c
  - |
    #!/bin/sh
    set -o errexit
    set -o xtrace

    docker tag bazel/experimental/nodejs:nodejs gcr.io/roava/nodejs:latest
    docker tag bazel/experimental/nodejs:debug  gcr.io/roava/nodejs:debug

images:
  - 'gcr.io/roava/nodejs:latest'
  - 'gcr.io/roava/nodejs:debug'

